name: Deploy

on:
  push:
    branches: [production]

jobs:
  push-to-production:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          known_hosts: ${{ secrets.AWS_KNOWN_HOSTS }}
      - name: Create Context
        run: docker context create --docker host=ssh://${{ secrets.AWS_USER }}@${{ secrets.AWS_IP }} webpack-starter
      - name: List Local Context
        run: docker context ls
      - name: Get Docker Version
        run: docker -v
      - name: Docker Down
        run: docker-compose -f docker-compose.prod.yml --context webpack-starter down
      - name: Docker Up
        run: docker-compose -f docker-compose.prod.yml --context webpack-starter up --build -d
